---
jobs:
- name: build-go-image
  public: true
  serial: true
  plan:
  - get: git-pipeline-docker-image
    trigger: true
  - put: docker-image
    params:
      build: git-pipeline-docker-image/ci/ci_image_unit_tests

resources:
- name: git-pipeline-docker-image
  type: git
  source:
    uri: git@github.com:starkandwayne/rdpg-boshrelease.git
    branch: develop-unit-tests
    private_key: {{github-private-key}}
    paths: [ci/ci_image_unit_tests/*]

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-unit-tests-image}}

